/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quanlicovid19;

import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class QuanLiCovidForm extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiCovidForm
     */
    
    private List<CachliInf> dscl;
    private List<InfCachLi> infds;
    public QuanLiCovidForm() {
        initComponents();
        dscl = new ArrayList(10);
        infds = new ArrayList(10);
    }
    public void themDSCL(CachliInf ds) {
       dscl.add(ds);  
    }
    public void themInfDSCL(InfCachLi inf) {
       infds.add(inf);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HoVaTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CMND = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        NamSinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        GioiTinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        QuocTich = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CongTyLamViec = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BoPhanLamViec = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TinhThanh = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        QuanHuyen = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        PhuongXa = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        SoNha = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        DienThoai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        KhaiBao = new javax.swing.JTextArea();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        Submit = new javax.swing.JButton();
        BaoHiem = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        DauHieu = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        TiepXuc = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Benh = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        ThaiKi = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        KhaiBaoYTe2 = new javax.swing.JTable();
        Delete = new javax.swing.JButton();
        Detail = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        KhaiBaoYTe1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TimKiemThongTin1 = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        TimKiemThongTin = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        HoVaTen1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        CMND1 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        NamSinh1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        GioiTinh1 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        QuocTich1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        CongTyLamViec1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        BoPhanLamViec1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        TinhThanh1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        QuanHuyen1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        PhuongXa1 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        SoNha1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        DienThoai1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        Email1 = new javax.swing.JTextField();
        Submit1 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        BatDau = new javax.swing.JFormattedTextField();
        jLabel42 = new javax.swing.JLabel();
        DiaDiem = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        TgianCL = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        MucDo = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        BaoHiem1 = new javax.swing.JTextField();
        Test = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        HinhThuc = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        Search1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        ThongTinCachLi2_1 = new javax.swing.JTable();
        Delete1 = new javax.swing.JButton();
        Detail1 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        ThongTinCachLi = new javax.swing.JTable();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ThongTinCachLi1 = new javax.swing.JTable();
        jScrollPane9 = new javax.swing.JScrollPane();
        ThongTinCachLi2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Họ và tên:");

        jLabel2.setText("Số CMND/Căn Cước:");

        jLabel3.setText("Năm Sinh");

        jLabel4.setText("Giới Tính");

        jLabel5.setText("Quốc Tịch:");

        jLabel6.setText("Bảo Hiểm Y Tế:");

        jLabel8.setText("Công ty làm việc:");

        jLabel9.setText("Bộ phận làm việc");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Địa chỉ liên lạc tại Việt Nam:");

        jLabel11.setText("Tỉnh Thành:");

        jLabel12.setText("Quận Huyện:");

        jLabel13.setText("Phường Xã:");

        jLabel14.setText("Số nhà, phố, tổ dân phố/thôn/đội:");

        jLabel15.setText("Điện Thoại:");

        jLabel16.setText("Email:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Trong vòng 14 ngày qua, Anh/Chị có đến quốc gia/vùng lãnh thổ nào (Có thể đi qua nhiều quốc gia): ");

        KhaiBao.setColumns(20);
        KhaiBao.setRows(5);
        jScrollPane1.setViewportView(KhaiBao);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Trong vòng 14 ngày qua, Anh/Chị có thấy xuất hiện dấu hiệu nào sau đây không? (*)");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Trong vòng 14 ngày qua, Anh/Chị có tiếp xúc với (*)");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Hiện tại Anh/Chị có các bệnh nào dưới đây (*)");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Hỏi Thêm:");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        jLabel50.setText("(Có/Không)");

        jLabel51.setText("(Sốt/ Ho/ Khó Thở/ Viêm Phổi/ Đau Họng/ Mệt Mỏi)");

        jLabel52.setText("( Người có biểu hiện (Sốt, ho, khó thở, Viêm phổi) (*)/ Người từ nước có bệnh COVID-19 (*)/ Người bệnh hoặc nghi ngờ, mắc bệnh COVID-19 (*) )\t \t");

        jLabel53.setText("( Bệnh gan mãn tính (*)/ Bệnh máu mãn tính (*)/ Bệnh phổi mãn tính (*)/ Bệnh thận mãn tính (*)/ Bệnh tim mạch (*)/ Huyết áp cao (*)/ Ung Thư (*)/ Tiểu Đường (*)/ Người nhận ghép tạng, Tủy xương (*)/ Suy giảm miễn dịch (*) )");

        jLabel54.setText("Bạn có đang trong thời gian thai kỳ hay không? (*)");

        jLabel55.setText("(Có/Không)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel53)
                        .addGap(0, 158, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SoNha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(TinhThanh, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(CongTyLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel9)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(BoPhanLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(QuanHuyen))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(43, 43, 43)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(18, 18, 18)
                                                .addComponent(CMND, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(18, 18, 18)
                                                .addComponent(QuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(BaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel50))))
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel18)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DauHieu, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel51)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Benh))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel52)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(TiepXuc))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel54)
                        .addGap(18, 18, 18)
                        .addComponent(ThaiKi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Submit)
                                .addGap(276, 276, 276))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(NamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(QuocTich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(BaoHiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CongTyLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(BoPhanLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TinhThanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(QuanHuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(PhuongXa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(SoNha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DauHieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(TiepXuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addGap(10, 10, 10)
                .addComponent(jLabel20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Benh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel53)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel54)
                            .addComponent(ThaiKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel55))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Submit)
                        .addGap(20, 20, 20))))
        );

        jTabbedPane1.addTab("Khai báo y tế", jPanel1);

        jLabel22.setText("Tìm Kiếm:");

        KhaiBaoYTe2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CMND/CCCD", "Lịch trình ", "Dấu hiệu", "Tiếp xúc", "Bệnh ", "Trong thai kì"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(KhaiBaoYTe2);

        Delete.setText("Xóa");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        Detail.setText("Chi Tiết");
        Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetailActionPerformed(evt);
            }
        });

        Edit.setText("Chỉnh Sửa");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        KhaiBaoYTe1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và Tên", "CMND/CCCD", "Năm Sinh", "Giới Tính", "Quốc Tịch", "Bảo Hiểm Y Tế", "Công Ty ", "Bộ Phận", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ));
        jScrollPane3.setViewportView(KhaiBaoYTe1);

        jLabel23.setText("Thông Tin Cá Nhân");

        jLabel24.setText("Thông tin sức khỏe khai báo");

        TimKiemThongTin1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CMND/CCCD", "Lịch Trình", "Dấu Hiệu", "Tiếp Xúc", "Bệnh", "Trong Thai Kì"
            }
        ));
        jScrollPane6.setViewportView(TimKiemThongTin1);

        TimKiemThongTin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và Tên", "CMND/CCCD", "Năm SInh", "Giới Tính", "Quốc Tịch", "Bảo Hiểm Y Tế", "Công ty", "Bộ Phận", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ));
        jScrollPane7.setViewportView(TimKiemThongTin);

        jButton1.setText("Tim Kiem");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Delete)
                                .addGap(308, 308, 308)
                                .addComponent(Detail)
                                .addGap(289, 289, 289)
                                .addComponent(Edit)
                                .addGap(0, 401, Short.MAX_VALUE))
                            .addComponent(jScrollPane6)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel23))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel22)
                                .addGap(18, 18, 18)
                                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(1, 1, 1)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete)
                    .addComponent(Detail)
                    .addComponent(Edit))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(409, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Thông Tin Khai Báo Y Tế", jPanel2);

        jLabel25.setText("Họ và tên:");

        jLabel26.setText("Số CMND/Căn Cước:");

        jLabel27.setText("Năm Sinh");

        jLabel28.setText("Giới Tính");

        jLabel29.setText("Quốc Tịch:");

        jLabel30.setText("Bảo Hiểm Y Tế:");

        jLabel31.setText("Công ty làm việc:");

        jLabel32.setText("Bộ phận làm việc");

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("Địa chỉ liên lạc tại Việt Nam:");

        jLabel34.setText("Tỉnh Thành:");

        jLabel35.setText("Quận Huyện:");

        jLabel36.setText("Phường Xã:");

        jLabel37.setText("Số nhà, phố, tổ dân phố/thôn/đội:");

        jLabel38.setText("Điện Thoại:");

        jLabel39.setText("Email:");

        Submit1.setText("Submit");
        Submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit1ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel40.setText("Địa chỉ liên lạc tại Việt Nam:");

        jLabel41.setText("Thời gian bắt đầu cách li:");

        BatDau.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLabel42.setText("Địa điểm cách li:");

        jLabel43.setText("Thời gian cách li:");

        jLabel44.setText("Mức độ cách li:");

        jLabel45.setText("Đã test covid chưa?");

        jLabel46.setText("Hình thức test:");

        jLabel56.setText("Chưa/Rồi");

        jLabel57.setText("Yes/No");

        jLabel58.setText("Test Nhanh/ Test PCR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(29, 29, 29)
                        .addComponent(BatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(jLabel42)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                        .addComponent(DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel27))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(HoVaTen1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(NamSinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel28)
                                        .addGap(18, 18, 18)
                                        .addComponent(GioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addGap(18, 18, 18)
                                        .addComponent(CMND1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(QuocTich1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44)
                                        .addComponent(jLabel30)
                                        .addGap(26, 26, 26)
                                        .addComponent(BaoHiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel57))))
                            .addComponent(jLabel33)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DienThoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel40)
                            .addComponent(jLabel46)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel45))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(Test, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31)
                                        .addComponent(jLabel56))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(52, 52, 52)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(HinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel58))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(TgianCL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(39, 39, 39)
                                                .addComponent(jLabel44)
                                                .addGap(37, 37, 37)
                                                .addComponent(MucDo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(0, 474, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PhuongXa1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SoNha1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TinhThanh1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel35))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(18, 18, 18)
                                .addComponent(CongTyLamViec1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel32)))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(BoPhanLamViec1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(QuanHuyen1)))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(Submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(HoVaTen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(CMND1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(NamSinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(GioiTinh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(QuocTich1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(BaoHiem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel57))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(CongTyLamViec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(BoPhanLamViec1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(TinhThanh1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(QuanHuyen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(PhuongXa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(SoNha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(DienThoai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(Email1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(BatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42)
                    .addComponent(DiaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel43)
                    .addComponent(TgianCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel44)
                    .addComponent(MucDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(Test, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel56))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel46)
                    .addComponent(HinhThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(Submit1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        jTabbedPane1.addTab("Khai báo Thông tin cách li", jPanel4);

        jLabel47.setText("Tìm Kiếm:");

        ThongTinCachLi2_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CMND/CCCD", "Thời gian bắt đầu cách li", "Thời gian cách li", "Mức độ cách li", "Địa điểm cách li", "Đã test chưa?", "Hình thức test"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(ThongTinCachLi2_1);

        Delete1.setText("Xóa");
        Delete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Delete1ActionPerformed(evt);
            }
        });

        Detail1.setText("Chi Tiết");
        Detail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Detail1ActionPerformed(evt);
            }
        });

        Edit1.setText("Chỉnh Sửa");
        Edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Edit1ActionPerformed(evt);
            }
        });

        ThongTinCachLi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và Tên", "CMND/CCCD", "Năm Sinh", "Giới Tính", "Quốc Tịch", "Bảo Hiểm Y Tế", "Công Ty ", "Bộ Phận", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(ThongTinCachLi);

        jLabel48.setText("Thông Tin Cá Nhân");

        jLabel49.setText("Thông tin sức khỏe khai báo");

        ThongTinCachLi1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Họ và Tên", "CMND/CCCD", "Năm Sinh", "Giới Tính", "Quốc Tịch", "Bảo Hiểm Y Tế", "Công Ty ", "Bộ Phận", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(ThongTinCachLi1);

        ThongTinCachLi2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CMND/CCCD", "Thời gian bắt đầu cách li", "Thời gian cách li", "Mức độ cách li", "Địa điểm cách li", "Đã test chưa?", "Hình thức test"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(ThongTinCachLi2);

        jButton2.setText("Tim Kiem");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(152, 152, 152)
                                .addComponent(jLabel47)
                                .addGap(18, 18, 18)
                                .addComponent(Search1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(Delete1)
                                .addGap(308, 308, 308)
                                .addComponent(Detail1)
                                .addGap(289, 289, 289)
                                .addComponent(Edit1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel49))
                                .addGap(0, 1111, Short.MAX_VALUE))
                            .addComponent(jScrollPane8)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane9))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane5)
                    .addContainerGap()))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel47)
                    .addComponent(Search1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(1, 1, 1)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel49)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete1)
                    .addComponent(Detail1)
                    .addComponent(Edit1))
                .addGap(56, 56, 56))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(59, 59, 59)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(423, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Thông Tin Cách li", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String hovaten = HoVaTen.getText();
        String cmnd = CMND.getText();
        String namSinh=NamSinh.getText();
        String gioiTinh =GioiTinh.getText();
        String quocTich = QuocTich.getText();
        String congty = CongTyLamViec.getText();
        String bophan = BoPhanLamViec.getText();
        String tinhThanh = TinhThanh.getText();
        String quanHuyen = QuanHuyen.getText();
        String phuongXa = PhuongXa.getText();
        String soNha = SoNha.getText();
        String dienThoai = DienThoai.getText();
        String mail = Email.getText();
        String khaiBao = KhaiBao.getText();
        String baoHiem= BaoHiem.getText();
        String dauHieu=DauHieu.getText();
        String tiepXuc =TiepXuc.getText();
        String benh =Benh.getText();
        String thaiKi=ThaiKi.getText();
        String diachi = soNha+" "+phuongXa+" "+quanHuyen+" "+tinhThanh;
        CachliInf infcl = new CachliInf(hovaten, cmnd, namSinh, gioiTinh, quocTich, baoHiem, congty, bophan, diachi, dienThoai, mail,khaiBao,dauHieu,tiepXuc,benh,thaiKi);
        DefaultTableModel KhaiBaoYTe = (DefaultTableModel) KhaiBaoYTe1.getModel();
        DefaultTableModel KhaiBaoYTe1 = (DefaultTableModel) KhaiBaoYTe2.getModel();
        KhaiBaoYTe.addRow(new Object[]{hovaten,cmnd,namSinh,gioiTinh,quocTich,baoHiem,congty,bophan,diachi,dienThoai,mail});
        KhaiBaoYTe1.addRow(new Object[]{cmnd,khaiBao,dauHieu,tiepXuc,benh,thaiKi});
        themDSCL(infcl);
        JOptionPane.showMessageDialog(null,"Khai Báo Thành Công!");
        HoVaTen.setText("");
        CMND.setText("");
        NamSinh.setText("");
        GioiTinh.setText("");
        QuocTich.setText("");
        CongTyLamViec.setText("");
        BoPhanLamViec.setText("");
        TinhThanh.setText("");
        QuanHuyen.setText("");
        PhuongXa.setText("");
        SoNha.setText("");
        DienThoai.setText("");
        Email.setText("");
        KhaiBao.setText("");
        BaoHiem.setText("");
        DauHieu.setText("");
        TiepXuc.setText("");
        Benh.setText("");
        ThaiKi.setText("");
    }//GEN-LAST:event_SubmitActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        DefaultTableModel khaiBaoYTe = (DefaultTableModel) KhaiBaoYTe1.getModel();
        DefaultTableModel khaiBaoYTe1 = (DefaultTableModel) KhaiBaoYTe2.getModel();
        int i = KhaiBaoYTe1.getSelectedRow();
        if(KhaiBaoYTe1.getSelectedRowCount()==1){
            khaiBaoYTe.removeRow(i);
            khaiBaoYTe1.removeRow(i);
            dscl.remove(i);
            JOptionPane.showMessageDialog(this,"Data is deleted");
        } else{
            if(KhaiBaoYTe1.getRowCount()==0){JOptionPane.showMessageDialog(this,"Table is empty");} 
            else {
                JOptionPane.showMessageDialog(this,"Please select signle row for delete");
            }
        }
        
    }//GEN-LAST:event_DeleteActionPerformed
    Object[][] data = null;
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
       DefaultTableModel khaiBaoYTe = (DefaultTableModel) KhaiBaoYTe1.getModel();
       DefaultTableModel khaiBaoYTe1 = (DefaultTableModel) KhaiBaoYTe2.getModel();
       CachliInf ds;
       int i = KhaiBaoYTe1.getSelectedRow();
      if (KhaiBaoYTe1.getSelectedRow() == -1) {
            if (KhaiBaoYTe1.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Table is empty");
            } else {
                JOptionPane.showMessageDialog(this,"You must select a index");
            }
        } else {
        String hovaten = JOptionPane.showInputDialog("Họ Và Tên");
        String cmnd = JOptionPane.showInputDialog("CMND/CCCD");
        String namSinh=JOptionPane.showInputDialog("Năm Sinh");
        String gioiTinh =JOptionPane.showInputDialog("Giới Tính");
        String quocTich = JOptionPane.showInputDialog("Quốc Tịch");
        String congty = JOptionPane.showInputDialog("Công Ty");
        String bophan = JOptionPane.showInputDialog("Bộ phận làm việc");
        String diaChi = JOptionPane.showInputDialog("Địa Chỉ");
        String dienThoai = JOptionPane.showInputDialog("Số Điện Thoại");
        String mail = JOptionPane.showInputDialog("Email");
        String baoHiem= JOptionPane.showInputDialog("Bao Hiem");
        if (hovaten.equals("")){hovaten = (String) khaiBaoYTe.getValueAt( i, 0);}
        if (cmnd.equals("")){cmnd = (String) khaiBaoYTe.getValueAt( i, 1);}
        if (namSinh.equals("")){namSinh = (String) khaiBaoYTe.getValueAt( i, 2);}
        if (gioiTinh.equals("")){gioiTinh = (String) khaiBaoYTe.getValueAt( i, 3);}
        if (quocTich.equals("")){quocTich = (String) khaiBaoYTe.getValueAt( i, 4);}
        if (baoHiem.equals("")){baoHiem = (String) khaiBaoYTe.getValueAt( i, 5);}
        if (congty.equals("")){congty = (String) khaiBaoYTe.getValueAt( i, 6);}
        if (bophan.equals("")){bophan = (String) khaiBaoYTe.getValueAt( i, 7);}
        if (diaChi.equals("")){diaChi = (String) khaiBaoYTe.getValueAt( i, 8);}
        if (dienThoai.equals("")){dienThoai = (String) khaiBaoYTe.getValueAt( i, 9);}
        if (mail.equals("")){mail = (String) khaiBaoYTe.getValueAt( i, 10);}
        khaiBaoYTe.setValueAt(hovaten, i, 0);
        khaiBaoYTe.setValueAt(cmnd, i, 1);
        khaiBaoYTe.setValueAt(namSinh, i, 2);
        khaiBaoYTe.setValueAt(gioiTinh, i, 3);
        khaiBaoYTe.setValueAt(quocTich, i, 4);
        khaiBaoYTe.setValueAt(baoHiem, i, 5);
        khaiBaoYTe.setValueAt(congty, i, 6);
        khaiBaoYTe.setValueAt(bophan, i, 7);
        khaiBaoYTe.setValueAt(diaChi, i, 8);
        khaiBaoYTe.setValueAt(dienThoai, i, 9);
        khaiBaoYTe.setValueAt(mail, i, 10);
        khaiBaoYTe1.setValueAt(cmnd, i, 0);
        ds = new CachliInf(hovaten, cmnd, namSinh, gioiTinh, quocTich,baoHiem,congty, bophan, diaChi,dienThoai, mail, (String) khaiBaoYTe1.getValueAt( i, 1), (String) khaiBaoYTe1.getValueAt( i, 2), (String) khaiBaoYTe1.getValueAt( i, 3), (String) khaiBaoYTe1.getValueAt( i, 4), (String) khaiBaoYTe1.getValueAt( i, 5));
        dscl.set(i,ds);
        JOptionPane.showMessageDialog(this,"Update successful");
        }
      
  
      
    }//GEN-LAST:event_EditActionPerformed
    public void TimKiem(String CMND){
         DefaultTableModel TimKiem = (DefaultTableModel) TimKiemThongTin.getModel();
         DefaultTableModel TimKiem1 = (DefaultTableModel) TimKiemThongTin1.getModel();
         TimKiem.setNumRows(0);
         TimKiem1.setNumRows(0);
         for(CachliInf cl:dscl){
             if(CMND.equals(cl.getCMND())){
                  TimKiem.addRow(new Object[]{cl.getHovaTen(),cl.CMND,cl.getNamSinh(),cl.getGioiTinh(),cl.getQuocTich(),cl.getBHYT(),cl.getCty(),cl.getBoPhan(),cl.getDiaChi(),cl.getSDT(),cl.getEmail()});
                  TimKiem1.addRow(new Object[]{cl.getCMND(),cl.getkhaiBao(),cl.getdauHieu(),cl.gettiepXuc(),cl.getbenh(),cl.getthaiKi()});
             }
         }
    }
    public static String Hoten;
    public static String CMND_CCCD;
    public static String Nam_Sinh;
    public static String Gioi_Tinh;
    public static String Quoc_Tich;
    public static String BaoHiemYTe;
    public static String Cty;
    public static String BoPhan;
    public static String Diachi;
    public static String SDThoai;
    public static String Mail;
    public static String LichTrinh;
    public static String Dau_Hieu;
    public static String Txuc;
    public static String BenhLienQuan;
    public static String Thai_Ki;
    public static String test;
    public static String Batdau;
    public static String TgianCl;
    public static String mucDo;
    public static String Diadiem;
    public static String hinhThuc;
    
    
    private void DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetailActionPerformed
        
       DefaultTableModel khaiBaoYTe = (DefaultTableModel) KhaiBaoYTe1.getModel();
       DefaultTableModel khaiBaoYTe1 = (DefaultTableModel) KhaiBaoYTe2.getModel();
       int i = KhaiBaoYTe1.getSelectedRow();
       Hoten = (String) khaiBaoYTe.getValueAt( i, 0);
       Nam_Sinh = (String) khaiBaoYTe.getValueAt( i, 2);
       CMND_CCCD = (String) khaiBaoYTe.getValueAt( i, 1);
       Gioi_Tinh = (String) khaiBaoYTe.getValueAt( i, 3);
       Quoc_Tich = (String) khaiBaoYTe.getValueAt( i, 4);
       BaoHiemYTe = (String) khaiBaoYTe.getValueAt( i, 5);
       Cty = (String) khaiBaoYTe.getValueAt( i, 6);
       BoPhan = (String) khaiBaoYTe.getValueAt( i, 7);
       Diachi = (String) khaiBaoYTe.getValueAt( i, 8);
       SDThoai = (String) khaiBaoYTe.getValueAt( i, 9);
       Mail = (String) khaiBaoYTe.getValueAt( i, 10);
       LichTrinh = (String) khaiBaoYTe1.getValueAt( i, 1);
       Dau_Hieu = (String) khaiBaoYTe1.getValueAt( i, 2);
       Txuc = (String) khaiBaoYTe1.getValueAt( i, 3);
       BenhLienQuan = (String) khaiBaoYTe1.getValueAt( i, 4);
       Thai_Ki = (String) khaiBaoYTe1.getValueAt( i, 5);
       ChiTietKhaiBao khaibao = new ChiTietKhaiBao(CMND_CCCD);
        khaibao.setVisible(true);
    }//GEN-LAST:event_DetailActionPerformed

    private void Submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Submit1ActionPerformed
        String hovaten = HoVaTen1.getText();
        String cmnd = CMND1.getText();
        String namSinh=NamSinh1.getText();
        String gioiTinh =GioiTinh1.getText();
        String quocTich = QuocTich1.getText();
        String congty = CongTyLamViec1.getText();
        String bophan = BoPhanLamViec1.getText();
        String tinhThanh = TinhThanh1.getText();
        String quanHuyen = QuanHuyen1.getText();
        String phuongXa = PhuongXa1.getText();
        String soNha = SoNha1.getText();
        String dienThoai = DienThoai1.getText();
        String mail = Email1.getText();
        String baoHiem= BaoHiem1.getText();
        String batDau= BatDau.getText();
        String diaDiem =DiaDiem.getText();
        String Tgiancl =TgianCL.getText();
        String Mucdo=MucDo.getText();
        String test=Test.getText();
        String Hinhthuc=HinhThuc.getText();
        String diachi = soNha+" "+phuongXa+" "+quanHuyen+" "+tinhThanh;
        DefaultTableModel ThongTinCachli = (DefaultTableModel) ThongTinCachLi.getModel();
        DefaultTableModel ThongTinCachLi1 = (DefaultTableModel) ThongTinCachLi2_1.getModel();
        ThongTinCachli.addRow(new Object[]{hovaten,cmnd,namSinh,gioiTinh,quocTich,baoHiem,congty,bophan,diachi,dienThoai,mail});
        ThongTinCachLi1.addRow(new Object[]{cmnd,batDau,Tgiancl,Mucdo,diaDiem,test,Hinhthuc});
        InfCachLi infcl = new InfCachLi(hovaten, cmnd, namSinh, gioiTinh, quocTich, baoHiem, congty, bophan, diachi, dienThoai, mail,batDau,Tgiancl,Mucdo,diaDiem,test,Hinhthuc);
        themInfDSCL(infcl);
        JOptionPane.showMessageDialog(null,"Khai Báo Thông tin cách li Thành Công!");
        HoVaTen1.setText("");
        CMND1.setText("");
        NamSinh1.setText("");
        GioiTinh1.setText("");
        QuocTich1.setText("");
        CongTyLamViec1.setText("");
        BoPhanLamViec1.setText("");
        TinhThanh1.setText("");
        QuanHuyen1.setText("");
        PhuongXa1.setText("");
        SoNha1.setText("");
        DienThoai1.setText("");
        Email1.setText("");
        DiaDiem.setText("");
        TgianCL.setText("");
        Test.setText("");
        HinhThuc.setText("");
        MucDo.setText("");
        BatDau.setText("");
        BaoHiem1.setText("");
    }//GEN-LAST:event_Submit1ActionPerformed

    private void Edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Edit1ActionPerformed
       DefaultTableModel ThongTinCachli = (DefaultTableModel) ThongTinCachLi.getModel();
        DefaultTableModel ThongTinCachLi1 = (DefaultTableModel) ThongTinCachLi2_1.getModel();
        InfCachLi ds;
       int i = ThongTinCachLi.getSelectedRow();
      if (ThongTinCachLi.getSelectedRow() == -1) {
            if (ThongTinCachLi.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this,"Table is empty");
            } else {
                JOptionPane.showMessageDialog(this,"You must select a index");
            }
        } else {
        String hovaten = JOptionPane.showInputDialog("Họ Và Tên");
        String cmnd = JOptionPane.showInputDialog("CMND/CCCD");
        String namSinh=JOptionPane.showInputDialog("Năm Sinh");
        String gioiTinh =JOptionPane.showInputDialog("Giới Tính");
        String quocTich = JOptionPane.showInputDialog("Quốc Tịch");
        String congty = JOptionPane.showInputDialog("Công Ty");
        String bophan = JOptionPane.showInputDialog("Bộ phận làm việc");
        String diaChi = JOptionPane.showInputDialog("Địa Chỉ");
        String dienThoai = JOptionPane.showInputDialog("Số Điện Thoại");
        String mail = JOptionPane.showInputDialog("Email");
        String baoHiem= JOptionPane.showInputDialog("Bao Hiem");
        if (hovaten.equals("")){hovaten = (String) ThongTinCachli.getValueAt( i, 0);}
        if (cmnd.equals("")){cmnd = (String) ThongTinCachli.getValueAt( i, 1);}
        if (namSinh.equals("")){namSinh = (String) ThongTinCachli.getValueAt( i, 2);}
        if (gioiTinh.equals("")){gioiTinh = (String) ThongTinCachli.getValueAt( i, 3);}
        if (quocTich.equals("")){quocTich = (String) ThongTinCachli.getValueAt( i, 4);}
        if (baoHiem.equals("")){baoHiem = (String) ThongTinCachli.getValueAt( i, 5);}
        if (congty.equals("")){congty = (String) ThongTinCachli.getValueAt( i, 6);}
        if (bophan.equals("")){bophan = (String) ThongTinCachli.getValueAt( i, 7);}
        if (diaChi.equals("")){diaChi = (String) ThongTinCachli.getValueAt( i, 8);}
        if (dienThoai.equals("")){dienThoai = (String) ThongTinCachli.getValueAt( i, 9);}
        if (mail.equals("")){mail = (String) ThongTinCachli.getValueAt( i, 10);}
        ThongTinCachli.setValueAt(hovaten, i, 0);
        ThongTinCachli.setValueAt(cmnd, i, 1);
        ThongTinCachli.setValueAt(namSinh, i, 2);
        ThongTinCachli.setValueAt(gioiTinh, i, 3);
        ThongTinCachli.setValueAt(quocTich, i, 4);
        ThongTinCachli.setValueAt(baoHiem, i, 5);
        ThongTinCachli.setValueAt(congty, i, 6);
        ThongTinCachli.setValueAt(bophan, i, 7);
        ThongTinCachli.setValueAt(diaChi, i, 8);
        ThongTinCachli.setValueAt(dienThoai, i, 9);
        ThongTinCachli.setValueAt(mail, i, 10);
        ThongTinCachLi1.setValueAt(cmnd, i, 0);
        ds = new InfCachLi(hovaten, cmnd, namSinh, gioiTinh, quocTich,baoHiem,congty, bophan, diaChi,dienThoai, mail, (String) ThongTinCachli.getValueAt( i, 1), (String) ThongTinCachli.getValueAt( i, 2), (String) ThongTinCachli.getValueAt( i, 3), (String) ThongTinCachli.getValueAt( i, 4), (String) ThongTinCachli.getValueAt( i, 5),(String) ThongTinCachli.getValueAt( i, 6));
        infds.set(i,ds);
          JOptionPane.showMessageDialog(this,"Update successful");
        }
      
    }//GEN-LAST:event_Edit1ActionPerformed

    private void Delete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Delete1ActionPerformed
        DefaultTableModel ThongTinCachli = (DefaultTableModel) ThongTinCachLi.getModel();
        DefaultTableModel ThongTinCachLi1 = (DefaultTableModel) ThongTinCachLi2_1.getModel();
        int i = ThongTinCachLi.getSelectedRow();
        if(ThongTinCachLi.getSelectedRowCount()==1){
            ThongTinCachli.removeRow(i);
            ThongTinCachLi1.removeRow(i);
            infds.remove(i);
            JOptionPane.showMessageDialog(this,"Data is deleted");
        } else{
            if(ThongTinCachLi.getRowCount()==0){JOptionPane.showMessageDialog(this,"Table is empty");} 
            else {
                JOptionPane.showMessageDialog(this,"Please select signle row for delete");
            }
        }
    }//GEN-LAST:event_Delete1ActionPerformed

    private void Detail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Detail1ActionPerformed
       DefaultTableModel ThongTinCachli = (DefaultTableModel) ThongTinCachLi.getModel();
       DefaultTableModel ThongTinCachLi1 = (DefaultTableModel) ThongTinCachLi2_1.getModel();
       int i = ThongTinCachLi.getSelectedRow();
       Hoten = (String) ThongTinCachli.getValueAt( i, 0);
       Nam_Sinh = (String) ThongTinCachli.getValueAt( i, 2);
       CMND_CCCD = (String) ThongTinCachli.getValueAt( i, 1);
       Gioi_Tinh = (String) ThongTinCachli.getValueAt( i, 3);
       Quoc_Tich = (String) ThongTinCachli.getValueAt( i, 4);
       BaoHiemYTe = (String) ThongTinCachli.getValueAt( i, 5);
       Cty = (String) ThongTinCachli.getValueAt( i, 6);
       BoPhan = (String)ThongTinCachli.getValueAt( i, 7);
       Diachi = (String) ThongTinCachli.getValueAt( i, 8);
       SDThoai = (String) ThongTinCachli.getValueAt( i, 9);
       Mail = (String) ThongTinCachli.getValueAt( i, 10);
       Batdau = (String) ThongTinCachLi1.getValueAt( i, 1);
       TgianCl = (String) ThongTinCachLi1.getValueAt( i, 2);
       mucDo = (String) ThongTinCachLi1.getValueAt( i, 3);
       Diadiem = (String) ThongTinCachLi1.getValueAt( i, 4);
       test = (String) ThongTinCachLi1.getValueAt( i, 5);
       hinhThuc = (String) ThongTinCachLi1.getValueAt( i, 6);
       ChiTietCachLi khaibao = new ChiTietCachLi(CMND_CCCD);
        khaibao.setVisible(true);
    }//GEN-LAST:event_Detail1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String CMND = Search.getText();
        TimKiem(CMND);
    }//GEN-LAST:event_jButton1ActionPerformed
     public void TimKiem1(String CMND){
         DefaultTableModel TimKiem = (DefaultTableModel) ThongTinCachLi1.getModel();
         DefaultTableModel TimKiem1 = (DefaultTableModel) ThongTinCachLi2.getModel();
         TimKiem.setNumRows(0);
         TimKiem1.setNumRows(0);
         for(InfCachLi cl:infds){
             if(CMND.equals(cl.getCMND())){
                  TimKiem.addRow(new Object[]{cl.getHovaTen(),cl.CMND,cl.getNamSinh(),cl.getGioiTinh(),cl.getQuocTich(),cl.getBHYT(),cl.getCty(),cl.getBoPhan(),cl.getDiaChi(),cl.getSDT(),cl.getEmail()});
                  TimKiem1.addRow(new Object[]{cl.getCMND(),cl.getTgianBatDauCachLi(),cl.getTgianCachLi(),cl.getMucDo(),cl.getDiaDiem(),cl.getDaTest(),cl.getHinhThucTest()});
             }
         }
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String CMND = Search1.getText();
        TimKiem1(CMND);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiCovidForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiCovidForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiCovidForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiCovidForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiCovidForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BaoHiem;
    private javax.swing.JTextField BaoHiem1;
    private javax.swing.JFormattedTextField BatDau;
    private javax.swing.JTextField Benh;
    private javax.swing.JTextField BoPhanLamViec;
    private javax.swing.JTextField BoPhanLamViec1;
    private javax.swing.JTextField CMND;
    private javax.swing.JTextField CMND1;
    private javax.swing.JTextField CongTyLamViec;
    private javax.swing.JTextField CongTyLamViec1;
    private javax.swing.JTextField DauHieu;
    private javax.swing.JButton Delete;
    private javax.swing.JButton Delete1;
    private javax.swing.JButton Detail;
    private javax.swing.JButton Detail1;
    private javax.swing.JTextField DiaDiem;
    private javax.swing.JTextField DienThoai;
    private javax.swing.JTextField DienThoai1;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Edit1;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Email1;
    private javax.swing.JTextField GioiTinh;
    private javax.swing.JTextField GioiTinh1;
    private javax.swing.JTextField HinhThuc;
    private javax.swing.JTextField HoVaTen;
    private javax.swing.JTextField HoVaTen1;
    private javax.swing.JTextArea KhaiBao;
    private javax.swing.JTable KhaiBaoYTe1;
    private javax.swing.JTable KhaiBaoYTe2;
    private javax.swing.JTextField MucDo;
    private javax.swing.JTextField NamSinh;
    private javax.swing.JTextField NamSinh1;
    private javax.swing.JTextField PhuongXa;
    private javax.swing.JTextField PhuongXa1;
    private javax.swing.JTextField QuanHuyen;
    private javax.swing.JTextField QuanHuyen1;
    private javax.swing.JTextField QuocTich;
    private javax.swing.JTextField QuocTich1;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField Search1;
    private javax.swing.JTextField SoNha;
    private javax.swing.JTextField SoNha1;
    private javax.swing.JButton Submit;
    private javax.swing.JButton Submit1;
    private javax.swing.JTextField Test;
    private javax.swing.JTextField TgianCL;
    private javax.swing.JTextField ThaiKi;
    private javax.swing.JTable ThongTinCachLi;
    private javax.swing.JTable ThongTinCachLi1;
    private javax.swing.JTable ThongTinCachLi2;
    private javax.swing.JTable ThongTinCachLi2_1;
    private javax.swing.JTextField TiepXuc;
    private javax.swing.JTable TimKiemThongTin;
    private javax.swing.JTable TimKiemThongTin1;
    private javax.swing.JTextField TinhThanh;
    private javax.swing.JTextField TinhThanh1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
